# Details
title: "Made With ML"
tagline: "Applied ML · MLOps · Production"
description: "Learn how to responsibly develop, deploy and maintain applications that are made with ML."
url: "https://mwml.xyz"

# Build settings
baseurl: '/'
permalink: /:title/
highlighter: rouge
syntax_theme: monokai

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO tag
author:
  type: Organization
  name: "Made With ML"
  url: https://madewithml.com/
  twitter: madewithml
  picture: static/images/card.png
twitter:
  username: madewithml
  card: summary_large_image
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: static/images/card.png


# Custom vars
version: 1.0.0
signup_url: "https://fe6c7da2.sibforms.com/serve/MUIEAFGYHgdTB8z1ETUytFE5SHsrp701ue3uI0ZhqQabG9HLqFkvlFkmNY7g2MudzR7K7_V0dPboLFlvxpSlahMlc-yH5GzwvqopbY8n7QA3XZbM97fiEaUmX50McwTaa5zLfUlhD-cRO3rkTMb62fosmNQlPfUXP1YKJ8bQafRIzpSaCgVy7AeoIkPNyjBK2EsXmgB4U_0w-_Vk"

# Collections
collections:
  pages:
    output: true
  courses:
    output: true
  resources:
    output: true
  tags:
    output: true

# Feed
feed:
  collections:
    - pages
    - courses
    - resources
