# Details
title: "Made With ML"
tagline: "Applied ML · MLOps · Production"
description: "Learn how to responsibly deliver value with applied ML."
url: "https://madewithml.com"

# Build settings
baseurl: '/'
permalink: /:title/
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO tag
author:
  type: Organization
  name: "Made With ML"
  url: https://madewithml.com/
  twitter: madewithml
  picture: static/images/card.png
twitter:
  username: madewithml
  card: summary_large_image
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: static/images/card.png


# Custom vars
version: 1.0.0

# Collections
collections:
  pages:
    output: true
  courses:
    output: true
  resources:
    output: true
  tags:
    output: true

# Feed
feed:
  collections:
    - pages
    - courses
    - resources
