name: Build staging
on:
  push:
    branches:
    - staging
  pull_request:
    branches:
    - staging

jobs:
  documentation:
    name: Build mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
